name: virtual_clock
description: A Flutter package for virtual time manipulation. Speed up, pause, or travel through time to test streaks, bonuses, and scheduled other events.
version: 1.0.0-dev.2
homepage: https://github.com/djoks/virtual_clock
repository: https://github.com/djoks/virtual_clock
issue_tracker: https://github.com/djoks/virtual_clock/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  fake_async: ^1.3.3

topics:
  - time
  - testing
  - virtual-time
  - clock
  - debugging

flutter:
  fonts:
    - family: Space Mono
      fonts:
        - asset: assets/fonts/SpaceMono/SpaceMono-Regular.ttf
        - asset: assets/fonts/SpaceMono/SpaceMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/SpaceMono/SpaceMono-Italic.ttf
          style: italic
        - asset: assets/fonts/SpaceMono/SpaceMono-BoldItalic.ttf
          weight: 700
          style: italic

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
